-- AlterTable
ALTER TABLE "ERC721Trade" ALTER COLUMN "purchaseTransaction" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "SaleTransaction" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "tokenId" SET DATA TYPE VARCHAR(255);
